### ISSUE TITLE
InstagramBot

### ISSUE THREAD

**Issue by Dyckon** [oliveiradeflavio/python#3]
Sempre que tento usar o seu programa no pycharm eu não consigo, aparece isso dai e também não consigo baixar o selenium e o PySimpleGUI
![image](https://user-images.githubusercontent.com/82600430/148215590-7f0ad2cf-44c0-458b-bdc5-8036781b4467.png)

**Comment by flaviooliveira-code** [comment]
@Dyckon  verifique se tem o Python instalado no seu sistema. Através do Python instalado você irá conseguir instalar o Selenium e o PySimpleGUI usando o PIP (via terminal).


Pelo terminal ou CMD, dependendo de qual sistema operacional você esteja usando
![python_version](https://user-images.githubusercontent.com/12213640/148266119-d9f6a1bc-dd39-4bd0-94af-5c4cc9fc7864.png)

![pip_version](https://user-images.githubusercontent.com/12213640/148266225-e67aaa34-8e92-4783-82a5-e49ea5323b2f.png)


Com Python certificado que esteja instalado e o PIP, você irá conseguir instalar o restante bibliotecas.
